name: Build & Upload Site
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Setup Environment.
      run: |
        bundle install

    - name: Build site
      run: JEKYLL_ENV=production bundle exec jekyll build

    - name: Publish on merge
      if: ${{ github.ref == 'refs/heads/main' }}
      run: echo "I'm merging!"

    - name: Upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        localPath: ./_site/*
        remotePath: ./www/smartlab/build-${{ github.sha }}/
